# Generated by Django 5.1.7 on 2025-03-24 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_board_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forums.board'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
